### ISSUE TITLE
Change name of site, org, and repo to oselab

### ISSUE THREAD

**Issue by rickecon** [OpenSourceEcon/oselab#37]
@asmockler . I am changing the name of the organization to the Open Source Economics Laboratory (OSE Lab). As such, I want to change the name of this repo to `oselab`, and I am going to change the name of the GitHub organization to `OpenSourceEcon`. I wanted to let you know this in case changing the organization name and repo name changed any settings that you need.

**Comment by asmockler** [comment]
Sounds great. Go ahead and change the repo name, I will adjust anything internal following the change in GitHub
