### ISSUE TITLE
Publishing to oselab.org

### ISSUE THREAD

**Issue by rickecon** [OpenSourceEcon/oselab#47]
@asmockler . Heroku site looks good. What do you need to publish that to oselab.org? The current setup with the new images should be sufficient for me to start advertising the boot camp. I didn't understand the following request of yours.

> You will need to add CNAME records for the following:
>
> @ -> fluffy-lobster-7muh4gllrlhqqjtcdho0dqsu.herokudns.com.
> www -> tropical-carnotaurus-bu1eiejtjamgv6axld6ev4so.herokudns.com.
>
> Let me know once that is done and I will double check that SSL is working.

Let me know what you need from me for the oselab.org domain.

**Comment by hayleefay** [comment]
@rickecon -- You basically need to tell the domain that you bought that it is going to display the content that is at those URLs that Andy sent. The way to do that is to set up a CNAME record and an A record. Did you buy the domain from google domains? [If so, this should be helpful.](https://support.google.com/domains/answer/6353515?hl=en). Specifically the "How to set custom resource records" section.

@asmockler -- "Fluffy Lobster" is the best automated domain I have ever seen.

**Comment by rickecon** [comment]
From domains.google.com, I was able to get the `CNAME` custom resource record `www -> tropical-carnotaurus-bu1eiejtjamgv6axld6ev4so.herokudns.com`, but I couldn't get the `A` custom resource record `@ -> fluffy-lobster-7muh4gllrlhqqjtcdho0dqsu.herokudns.com`. The error said "Invalid data". @asmockler @hayleefay any ideas?
![screen shot 2019-02-19 at 2 28 23 pm](https://user-images.githubusercontent.com/4317690/53045316-ea0a0a80-3452-11e9-980f-6735627955f6.png)

**Comment by asmockler** [comment]
Use CNAME for both – so just change A to CNAME in your screenshot

**Comment by rickecon** [comment]
`CNAME` also doesn't work for `fluffy-lobster-7muh4gllrlhqqjtcdho0dqsu.herokudns.com`. The error is "CNAME records for the root domain are not supported". @asmockler 
![screen shot 2019-02-19 at 2 33 44 pm](https://user-images.githubusercontent.com/4317690/53045500-63096200-3453-11e9-9891-f1a14d14db41.png)

**Comment by asmockler** [comment]
Oh yeah, I forgot that google doesn't allow that. Ok, skip the fluffy lobster on (unfortunately) and add a redirect. Above that section, there is a section called "Synthetic records." Do a subdomain forward from `@` to `www`. Choose permanent redirect, forward path, and enable SSL. If it lets you do that, then we should be good to go

**Comment by asmockler** [comment]
(P.S. `https://www.oselab.org` is working! Just gotta get the root domain working as well)

**Comment by rickecon** [comment]
Ugh. "The SSL Certificate for this domain hasn't been created yet. This process may take up to 24 hours to complete." In this screenshot, I am showing the error I got as well as the inputs I gave in the gray panel. Any suggestions @asmockler?
![screen shot 2019-02-19 at 2 41 58 pm](https://user-images.githubusercontent.com/4317690/53045964-897bcd00-3454-11e9-80d9-846419f00e93.png)

**Comment by asmockler** [comment]
Eh, just edit it and disable SSL. I think we can still force it elsewhere and it isn't super necessary for what is there right now.

**Comment by asmockler** [comment]
It looks like the forwarding rule ends up on SSL after the redirect, so it is fine to disable it.

**Comment by rickecon** [comment]
Do I just edit the subdomain forward to disable SSL? Everything else the same?

**Comment by asmockler** [comment]
Correct

**Comment by rickecon** [comment]
OK. All looks good. What next?

**Comment by rickecon** [comment]
Looks like we're good on this issue.
